name: BPMN Validation

# Run the workflow on pull requests and pushes for any .bpmn file change
on: 
  pull_request:
    paths:
      - '**/*.bpmn'
  push:
    paths:
      - '**/*.bpmn'

jobs:
  validate-bpmn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Fetch base branch
      if: github.event_name == 'pull_request'
      run: |
        # Fetch the base branch explicitly to make it available for diff
        git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Get list of changed BPMN files
      id: changed_files
      run: |
        node validateBpmn.js ${{ steps.changed-files.outputs.all_changed_files }}